version: "3.0"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
    volumes:
      - home/ec2-user/test/gan_shmuel/one-db.sql-billing:/docker-entrypoint-initdb.d/one-db.sql
      - wdata:/var/lib/mysql/:rw
      # - ${TEAM_PATH}:/weight
    networks:
      - bridge

  web:
    build: ./app 
    ports:
      - "8081:5000"
    depends_on:
      - db
    container_name: localbilling
    links:
      - db
    networks:
      - blue_net
      - bridge
    
volumes:
  wdata:      
  
networks:
  blue_net: 
  bridge:
