version: "3.0"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
    volumes:
      - ./one-db.sql:/docker-entrypoint-initdb.d/one-db.sql
      - wdata:/var/lib/mysql/:rw
    networks:
      - bridge


  web:
    build: ./app 
    volumes:
      - ./app/in:/app/in
    ports:
      - "8081:5000"
    depends_on:
      - db
    container_name: localbilling
    links:
      - db
    networks:
      - blue_net
      - bridge
    
volumes:
  wdata:      
  
networks:
  blue_net: 
  bridge:

