version: "3.0"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./one-db.sql:/docker-entrypoint-initdb.d/one-db.sql

  web:
    build: ./app 
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
   