version: "3.0"
services:
  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8084:3306"
    volumes:
      # - ./one-db.sql:/docker-entrypoint-initdb.d/one-db.sql
      - wdata:/var/lib/mysql/:rw

  web:
    build: ./app
    # volumes:
    #   - ./app:/app
    ports:
      - "8082:5000"
    depends_on:
      - db

volumes:
  wdata: