version: "3.3"
services: 
  db:
    image: mysql:8
    volumes:
     - "db:/var/lib/mysql"
    environment:
     - MYSQL_ROOT_PASSWORD=1
    ports:     
      # <Port exposed> : < MySQL Port running inside container>
     - 3306:3306
# Names our volume
volumes:
  db:
  
